# llama.cpp 고정 커밋에 patches/*.patch 를 멱등 적용한다. 사용: include(<repo>/patches/apply.cmake)
set(_ling_root ${CMAKE_CURRENT_LIST_DIR}/..)
set(_ling_llama ${_ling_root}/third_party/llama.cpp)
file(GLOB _ling_patches ${CMAKE_CURRENT_LIST_DIR}/*.patch)
list(SORT _ling_patches)
file(LOCK ${CMAKE_CURRENT_LIST_DIR} DIRECTORY GUARD PROCESS)
foreach (p IN LISTS _ling_patches)
    execute_process(COMMAND git apply --reverse --check ${p} WORKING_DIRECTORY ${_ling_llama}
                    RESULT_VARIABLE already OUTPUT_QUIET ERROR_QUIET)
    if (NOT already EQUAL 0)
        execute_process(COMMAND git apply ${p} WORKING_DIRECTORY ${_ling_llama} RESULT_VARIABLE r)
        if (NOT r EQUAL 0)
            message(FATAL_ERROR "llama.cpp 패치 적용 실패: ${p}")
        endif ()
        message(STATUS "llama.cpp 패치 적용: ${p}")
    endif ()
endforeach ()
file(LOCK ${CMAKE_CURRENT_LIST_DIR} DIRECTORY RELEASE)
